const mongoose = require("mongoose");

const medicalDocumentSchema = new mongoose.Schema(
  {
    patient: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Patient",
      required: true,
    },

    uploadedBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
    },

    consultation: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Consultation",
    },

    // Original name the user gave the file
    originalName: {
      type: String,
      required: true,
      trim: true,
    },

    // Name stored on disk (generated by Multer to avoid conflicts)
    fileName: {
      type: String,
      required: true,
    },

    // Relative path from project root e.g. "uploads/1234567890-report.pdf"
    filePath: {
      type: String,
      required: true,
    },

    // MIME type e.g. "image/jpeg", "application/pdf"
    mimeType: {
      type: String,
      required: true,
    },

    // File size in bytes
    fileSize: {
      type: Number,
      required: true,
    },

    documentType: {
      type: String,
      enum: [
        "prescription",
        "lab_report",
        "discharge_summary",
        "xray",
        "scan",
        "other",
      ],
      default: "other",
    },

    // OCR-extracted text (filled later by ocrController)
    extractedText: {
      type: String,
      default: "",
    },

    // Whether OCR has been run on this document
    ocrProcessed: {
      type: Boolean,
      default: false,
    },

    // AI analysis of the extracted text (filled later by aiController)
    aiAnalysis: {
      summary: String,
      keyFindings: [String],
      recommendation: String,
    },

    notes: {
      type: String,
      trim: true,
    },
  },
  {
    timestamps: true,
  }
);

module.exports = mongoose.model("MedicalDocument", medicalDocumentSchema);
